### ISSUE TITLE
[StateProvider] 컴포넌트 유형별 셋팅 참고

### ISSUE THREAD

**Issue by skawnkk** [codesqurd-master-DD/todo-list#14]
로그데이터를 가져오는 작업 중에 modeType을 정리해봤고, 메시지를 어떻게 보내주냐에 따라
 stateProvider에서 보내줄 정보가 더 필요할것 같아 확인 부탁드려요 : )

**[modeType 유형 & 메시지]**
- add : column에 title을 등록하였습니다. 
- transfer: title을 prevColumn에서 currColumn으로 이동하였습니다. 
 **=>**prevColumn 이 필요합니다. (기획서내용)****
- update: title의 내용이 변경되었습니다. (간단하게 작성함)
- delete: title가 삭제되었습니다.
- 몇분전...표기 => 완료

이따 같이 정리해바욥 😀
@jjunyjjuny @adelakim5 @skawnkk

**Comment by adelakim5** [comment]
그럼 시간 key값도 필요하겠군요~

**Comment by adelakim5** [comment]
카드 이동 구현할 때 다시 보기로~ (시간 생각나면 넣자~)
