### ISSUE TITLE
[NavBar] 마크업_CSS질문

### ISSUE THREAD

**Issue by skawnkk** [codesqurd-master-DD/todo-list#8]
```
const iconX = styled.div`
  position: absolute;
  right: 80px;
  top: 50px;
  
`;

function LogStorage({ LogStorageDom }) {
  return (
    <>
      <LogStorageBlock className="logStorage appear" ref={LogStorageDom}>
        <iconX>
          <HiX></HiX>
        </iconX>

```
'iconX'이(가) 선언은 되었지만 해당 값이 읽히지는 않았습니다.ts(6133) 
라는 오류가 뜨면서 iconX의 css가 전혀 적용되지 않네요 ..?

질문겸 이슈연습이었습니다
답변주시면 감사하겠습니다😀

written by @skawnkk

**Comment by jjunyjjuny** [comment]
코드에 생략된 다른 부분도 볼 수 있을까요?

**Comment by skawnkk** [comment]
아 이거 해결했는데, styled컴포넌트 사용할때도 맨 앞글자가 대소문자 통일이 되어야 하나봐요.
IconX라고 고치니까 잘 되었네용 ㅎㅎㅎ 앞글자는 대문자롷ㅎ
